### ISSUE TITLE
unable to build epdfinfo program on termux

### ISSUE THREAD

**Issue by gbarnich** [vedang/pdftoolswiki#1]
Hi, I am unable to get the server working on termux, below the error message, any suggestions ?

~/pdf-tools $ ./server/autobuild -d
Failed to recognize this system, trying to continue.
---------------------------
 Configuring and compiling
---------------------------
./configure -q  && make clean && make -s
configure: error: Package requirements (poppler-glib >= 0.16.0) were not met:

Package 'xproto', required by 'x11', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables poppler_glib_CFLAGS
and poppler_glib_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
===========================
     Build failed.  ;o(
===========================

**Comment by vedang** [comment]
Please review the issues in `vedang/pdf-tools` to see if you can find an answer to your query. This is the wrong repo, it's the Wiki for `pdf-tools`

Closing this ticket, please re-open on `vedang/pdf-tools` if the problem persists after your search
